### ISSUE TITLE
panic: context deadline exceeded (Client.Timeout or context cancellation while reading body)

### ISSUE THREAD

**Issue by llnbe** [zqyangchn/hadoop_exporter#2]
{"Level":"warn","Time":"2021-06-25T20:19:28.818+0800","Caller":"hbase/parseExporterStatus.go:23","Message":"set hbase_node_status 0","error":"context deadline exceeded (Client.Timeout or context cancellation while reading body)"}
{"Level":"debug","Time":"2021-06-25T20:19:28.818+0800","Caller":"generic/Collect.go:56","Message":"Collect Metrics Information","Count":2}
panic: context deadline exceeded (Client.Timeout or context cancellation while reading body)

goroutine 35 [running]:
hadoop_exporter/generic.(*CollectGenericMetricsForPrometheus).CollectMetricsBackGround.func1(0xc0000b0000)
	/root/hadoop_exporter/generic/Collect.go:19 +0x2da
created by hadoop_exporter/generic.(*CollectGenericMetricsForPrometheus).CollectMetricsBackGround
	/root/hadoop_exporter/generic/Collect.go:17 +0x3f

**Comment by zqyangchn** [comment]
16 func (c *CollectGenericMetricsForPrometheus) CollectMetricsBackGround() {
 17     go func() {
 18         if err := c.CollectMetrics(); err != nil {
 19             panic(err)
 20         }
 21
 22         for range time.Tick(c.CollectInterval) {
 23             if err := c.CollectMetrics(); err != nil {
 24                 log.Warn("Collect Metrics Failed. ", zap.Error(err))
 25             }
 26         }
 27     }()
 28 }
这个是第一次程序启动的时候会搜集hbase 的信息失败导致的, 错误的原因应该是连接超时导致的, 程序只有第一次启动搜集信息失败的时候会 panic, 运行过程中只会打印 warning 日志

**Comment by llnbe** [comment]
连接超时的时间哪里可以指定，如HBASE 1.2 jmx 信息过大导致超时，超时时间可以设置长一些，比如3m

**Comment by zqyangchn** [comment]
![image](https://user-images.githubusercontent.com/30464173/123438491-512bc100-d603-11eb-8ed6-80d00aa438f1.png)

**Comment by zqyangchn** [comment]
generic/factory.go

**Comment by llnbe** [comment]
thanks

**Comment by llnbe** [comment]
panic: runtime error: index out of range [2] with length 0

goroutine 50 [running]:
hadoop_exporter/hbase.(*Collect).parseHbaseRegionServerRegions(0xc000188080, 0xc0002401e0, 0x8e3c80, 0xc000187800)
	/root/hadoop_exporter/hbase/parseRegionServerRegions.go:22 +0xfb0
hadoop_exporter/hbase.(*Collect).ParseUniqueMetrics(0xc000188080, 0xc0002401e0, 0x8e3c80, 0xc000187800)
	/root/hadoop_exporter/hbase/parseUniqueMetrics.go:31 +0x6d8
hadoop_exporter/generic.(*CollectGenericMetricsForPrometheus).ParseGenericMetrics(0xc000188080, 0xc0002401e0, 0xc00017a400, 0x1c, 0x20)
	/root/hadoop_exporter/generic/parseGenericMetrics.go:41 +0x33a
hadoop_exporter/generic.(*CollectGenericMetricsForPrometheus).CollectMetrics(0xc000188080, 0x0, 0x0)
	/root/hadoop_exporter/generic/Collect.go:99 +0x72d
hadoop_exporter/generic.(*CollectGenericMetricsForPrometheus).CollectMetricsBackGround.func1(0xc000188080)
	/root/hadoop_exporter/generic/Collect.go:18 +0x45
created by hadoop_exporter/generic.(*CollectGenericMetricsForPrometheus).CollectMetricsBackGround
	/root/hadoop_exporter/generic/Collect.go:17 +0x3f

**Comment by zqyangchn** [comment]
Hadoop:service=HBase,name=RegionServer,sub=Regions json 键^Namespace_([\w-]+)_table_([\w-]+)_region_([\w-]+)_metric_([\w-]+)$ 匹配失败导致的, 这个是hbase 2.1 的 json 格式, 我不清楚 hbase 1.2 的 json 格式
